import numpy as np

from strategy.base_Strategy import Strategy
from RBF_surrogate import RBF
from GP_surrogate import GP
from RBF_improved import RBF_improved

key = 2 # key = 0 時為RBF key = 1 時為GP key = 2 時為RBF_improved

# a3
class crossover_strategy(Strategy):
    '''
    
    '''

    def __init__(self, lb, ub, rng, m=None, poly_tail_min_ratio=1.5):
        '''
        Args:
            m: int, the number of candidate solutions to generate
        '''
        super().__init__(lb, ub, rng)

        d = len(lb)
        min_required = int(np.ceil(poly_tail_min_ratio * (2 * d + 1))) + 10
        self.m = m if m is not None else max(100, min_required)

    def strategy(self, DB, f):
        '''
        Args:
            DB: np.ndarray, shape (N, d), the database of solutions
            f: callable, the fitness evaluation function     
        
        Return:
            Dnew: np.ndarray, shape (m, d+1), the new data generated by the strategy
            
        '''

        # Get the best m solutions from the database
        P,Y_P = DB.get_nbest(self.m)
        m_actual, d = P.shape

        models = [RBF().fit(P,Y_P),
                  GP().fit(P,Y_P),
                  RBF_improved().fit(P,Y_P)]
        model = models[key]
        
        phi = self.rng.permutation(d)
        x_best = np.copy(P[0])

        # Iterate over each dimension in the permuted order
        for i in phi:
            P_t = np.tile(x_best, (m_actual, 1))
            P_t[:, i] = P[:, i]       # replace the i-th dimension with the values from the best solutions
            pred = model.predict(P_t) 

            best_index = np.argmin(pred)
            x_best[i] = P_t[best_index, i]

        x_best = self.clip(x_best) # check if the candidate solution is within the bounds
        D_new = [(x_best, float(f(x_best)))]

        return D_new
