import numpy as np

from base_Strategy import Strategy
from RBF import RBF

# a3
class crossover_strategy(Strategy):
    '''
    Input: Database DB, Real fitness evaluation f
    Output: New data Dnew
    1 Build local surrogate fl based on the best l data from DB;
    2 Calculate the local range [lb,ub] according to Eqs. 7 and 8 and data of fl;
    3 Obtain one candidate xc by minimizing fl using JADE in the local region;
    4 {xc, f(xc)} is added to Dnew;
    '''

    def __init__(self, lb, ub, rng, m=100):
        '''
        Args:
            m: int, the number of candidate solutions to generate
        '''
        super().__init__(lb, ub, rng)

        self.m=m

    def strategy(self, DB, f):
        '''
        Args:
            DB: np.ndarray, shape (N, d), the database of solutions
            f: callable, the fitness evaluation function     
        
        Return:
            Dnew: np.ndarray, shape (m, d+1), the new data generated by the strategy
            
        '''

        # Get the best m solutions from the database
        P,Y_P = DB.get_nbest(self.m)
        m_actual, d = P.shape

        model = RBF().fit(P,Y_P)

        phi = self.rng.permutation(d)
        x_best = np.copy(P[0])

        # Iterate over each dimension in the permuted order
        for i in phi:
            P_t = np.tile(x_best, (m_actual, 1))
            P_t[:, i] = P[:, i]       # replace the i-th dimension with the values from the best solutions
            pred = model.predict(P_t) 

            best_index = np.argmin(pred)
            x_best[i] = P_t[best_index, i]

        x_best = self.clip(x_best) # check if the candidate solution is within the bounds
        D_new = [x_best, float(f(x_best))]

        return D_new    
        

